apiVersion: v1
kind: PersistentVolume
metadata:
  name: the-nginx-pv
spec:
  storageClassName: "lab9"
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nginx-pvc-data 
