apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-nginx-pvc
spec:
  storageClassName: "lab9"
  volumeName: the-nginx-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
