apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host-path
  labels:
    app: nginx-host-path
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-host-path
  template:
    metadata:
      labels:
        app: nginx-host-path
    spec:
      volumes:
        # TODO complete
        - name: host-html
          hostPath:
            # Path on the host
            path: /mnt/hostPath
            # 'DirectoryOrCreate' create dir if not exists
            type: DirectoryOrCreate
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
            name: "http-server"
        volumeMounts:
          # TODO complete
          - name: host-html
            mountPath: /usr/share/nginx/html/volume
